version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000/api
